PACKAGE_NAME="imac-poweroff"
PACKAGE_VERSION="1.0.0"
BUILT_MODULE_NAME[0]="imac_sleep_test"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
